FROM roundcube/roundcubemail:latest

MAINTAINER DRIVER-EU

LABEL name="RoundCube drive-eu"
LABEL version="1.0"
LABEL description="RoundCube drive-eu"

COPY roundcube_logo.png /var/www/html/skins/larry/images/roundcube_logo.png
COPY roundcube_logo.png /usr/src/roundcubemail/skins/larry/images/

