/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Mail server gateway
 * Mail server
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface MailData
 */
export interface MailData {
    /**
     * 
     * @type {string}
     * @memberof MailData
     */
    From: string;
    /**
     * 
     * @type {string}
     * @memberof MailData
     */
    To: string;
    /**
     * 
     * @type {string}
     * @memberof MailData
     */
    Subject: string;
}


/**
 * ManagementApi - fetch parameter creator
 * @export
 */
export const ManagementApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Send an e-mail to test mail server gateway
         * @param {MailData} MailData 
         * @param {boolean} UseKafka 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendTestMail(MailData: MailData, UseKafka: boolean, options: any = {}): FetchArgs {
            // verify required parameter 'MailData' is not null or undefined
            if (MailData === null || MailData === undefined) {
                throw new RequiredError('MailData','Required parameter MailData was null or undefined when calling sendTestMail.');
            }
            // verify required parameter 'UseKafka' is not null or undefined
            if (UseKafka === null || UseKafka === undefined) {
                throw new RequiredError('UseKafka','Required parameter UseKafka was null or undefined when calling sendTestMail.');
            }
            const localVarPath = `/management/SendMail`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (UseKafka !== undefined) {
                localVarQueryParameter['useKafka'] = UseKafka;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"MailData" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(MailData || {}) : (MailData || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ManagementApi - functional programming interface
 * @export
 */
export const ManagementApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Send an e-mail to test mail server gateway
         * @param {MailData} MailData 
         * @param {boolean} UseKafka 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendTestMail(MailData: MailData, UseKafka: boolean, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
            const localVarFetchArgs = ManagementApiFetchParamCreator(configuration).sendTestMail(MailData, UseKafka, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * ManagementApi - factory interface
 * @export
 */
export const ManagementApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @summary Send an e-mail to test mail server gateway
         * @param {MailData} MailData 
         * @param {boolean} UseKafka 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendTestMail(MailData: MailData, UseKafka: boolean, options?: any) {
            return ManagementApiFp(configuration).sendTestMail(MailData, UseKafka, options)(fetch, basePath);
        },
    };
};

/**
 * ManagementApi - object-oriented interface
 * @export
 * @class ManagementApi
 * @extends {BaseAPI}
 */
export class ManagementApi extends BaseAPI {
    /**
     * 
     * @summary Send an e-mail to test mail server gateway
     * @param {MailData} MailData 
     * @param {boolean} UseKafka 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementApi
     */
    public sendTestMail(MailData: MailData, UseKafka: boolean, options?: any) {
        return ManagementApiFp(this.configuration).sendTestMail(MailData, UseKafka, options)(this.fetch, this.basePath);
    }

}

