/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Mail server gateway
 * Mail server
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface AddMailAccountResultImpl
 */
export interface AddMailAccountResultImpl {
    /**
     * 
     * @type {string}
     * @memberof AddMailAccountResultImpl
     */
    Msg: string;
}

/**
 * 
 * @export
 * @interface DeleteMailAccountResultImpl
 */
export interface DeleteMailAccountResultImpl {
    /**
     * 
     * @type {string}
     * @memberof DeleteMailAccountResultImpl
     */
    Msg: string;
}

/**
 * 
 * @export
 * @interface MailAccountsResultImpl
 */
export interface MailAccountsResultImpl {
    /**
     * 
     * @type {Array<string>}
     * @memberof MailAccountsResultImpl
     */
    Accounts: Array<string>;
}

/**
 * 
 * @export
 * @interface MailData
 */
export interface MailData {
    /**
     * 
     * @type {string}
     * @memberof MailData
     */
    From: string;
    /**
     * 
     * @type {string}
     * @memberof MailData
     */
    To: string;
    /**
     * 
     * @type {string}
     * @memberof MailData
     */
    Subject: string;
    /**
     * 
     * @type {string}
     * @memberof MailData
     */
    Content: string;
}

/**
 * 
 * @export
 * @interface ResetResultImpl
 */
export interface ResetResultImpl {
    /**
     * 
     * @type {string}
     * @memberof ResetResultImpl
     */
    Msg: string;
}

/**
 * 
 * @export
 * @interface SimulationEntityPostData
 */
export interface SimulationEntityPostData {
    /**
     * 
     * @type {string}
     * @memberof SimulationEntityPostData
     */
    PostAsJson: string;
}

/**
 * 
 * @export
 * @interface Statusresult
 */
export interface Statusresult {
    /**
     * 
     * @type {string}
     * @memberof Statusresult
     */
    StatusAsJson: string;
}


/**
 * ManagementApi - fetch parameter creator
 * @export
 */
export const ManagementApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add mail account to mail server (e.g. \"user@world.com\") 
         * @summary Add mail account
         * @param {string} Password The mail account password
         * @param {string} Account The mail account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAccount(Password: string, Account: string, options: any = {}): FetchArgs {
            // verify required parameter 'Password' is not null or undefined
            if (Password === null || Password === undefined) {
                throw new RequiredError('Password','Required parameter Password was null or undefined when calling addAccount.');
            }
            // verify required parameter 'Account' is not null or undefined
            if (Account === null || Account === undefined) {
                throw new RequiredError('Account','Required parameter Account was null or undefined when calling addAccount.');
            }
            const localVarPath = `/management/AddMailAccount`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (Password !== undefined) {
                localVarQueryParameter['password'] = Password;
            }

            if (Account !== undefined) {
                localVarQueryParameter['account'] = Account;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete mail account to mail server \"user@world.com\" 
         * @summary Delete mail account
         * @param {string} Account The mail account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAccount(Account: string, options: any = {}): FetchArgs {
            // verify required parameter 'Account' is not null or undefined
            if (Account === null || Account === undefined) {
                throw new RequiredError('Account','Required parameter Account was null or undefined when calling deleteAccount.');
            }
            const localVarPath = `/management/DeleteMailAccount`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (Account !== undefined) {
                localVarQueryParameter['account'] = Account;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get status of server
         * @summary Get status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus(options: any = {}): FetchArgs {
            const localVarPath = `/management/GetStatus`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get mail accounts
         * @summary Get mail accounts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mailAccounts(options: any = {}): FetchArgs {
            const localVarPath = `/management/MailAccounts`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Reset database
         * @summary Reset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reset(options: any = {}): FetchArgs {
            const localVarPath = `/management/Reset`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Send an e-mail to test mail server gateway
         * @param {MailData} MailData 
         * @param {boolean} UseKafka 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendTestMail(MailData: MailData, UseKafka: boolean, options: any = {}): FetchArgs {
            // verify required parameter 'MailData' is not null or undefined
            if (MailData === null || MailData === undefined) {
                throw new RequiredError('MailData','Required parameter MailData was null or undefined when calling sendTestMail.');
            }
            // verify required parameter 'UseKafka' is not null or undefined
            if (UseKafka === null || UseKafka === undefined) {
                throw new RequiredError('UseKafka','Required parameter UseKafka was null or undefined when calling sendTestMail.');
            }
            const localVarPath = `/management/SendMail`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (UseKafka !== undefined) {
                localVarQueryParameter['useKafka'] = UseKafka;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"MailData" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(MailData || {}) : (MailData || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Test JSON ISimulationEntityPost injection (direct or KAFKA)
         * @param {SimulationEntityPostData} SimulationEntityPostData 
         * @param {boolean} UseKafka 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testSimulationEntityPost(SimulationEntityPostData: SimulationEntityPostData, UseKafka: boolean, options: any = {}): FetchArgs {
            // verify required parameter 'SimulationEntityPostData' is not null or undefined
            if (SimulationEntityPostData === null || SimulationEntityPostData === undefined) {
                throw new RequiredError('SimulationEntityPostData','Required parameter SimulationEntityPostData was null or undefined when calling testSimulationEntityPost.');
            }
            // verify required parameter 'UseKafka' is not null or undefined
            if (UseKafka === null || UseKafka === undefined) {
                throw new RequiredError('UseKafka','Required parameter UseKafka was null or undefined when calling testSimulationEntityPost.');
            }
            const localVarPath = `/management/TestSimulationEntityPost`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PUT' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (UseKafka !== undefined) {
                localVarQueryParameter['useKafka'] = UseKafka;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"SimulationEntityPostData" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(SimulationEntityPostData || {}) : (SimulationEntityPostData || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ManagementApi - functional programming interface
 * @export
 */
export const ManagementApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Add mail account to mail server (e.g. \"user@world.com\") 
         * @summary Add mail account
         * @param {string} Password The mail account password
         * @param {string} Account The mail account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAccount(Password: string, Account: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<AddMailAccountResultImpl> {
            const localVarFetchArgs = ManagementApiFetchParamCreator(configuration).addAccount(Password, Account, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Delete mail account to mail server \"user@world.com\" 
         * @summary Delete mail account
         * @param {string} Account The mail account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAccount(Account: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<DeleteMailAccountResultImpl> {
            const localVarFetchArgs = ManagementApiFetchParamCreator(configuration).deleteAccount(Account, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Get status of server
         * @summary Get status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Statusresult> {
            const localVarFetchArgs = ManagementApiFetchParamCreator(configuration).getStatus(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Get mail accounts
         * @summary Get mail accounts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mailAccounts(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<MailAccountsResultImpl> {
            const localVarFetchArgs = ManagementApiFetchParamCreator(configuration).mailAccounts(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Reset database
         * @summary Reset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reset(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<ResetResultImpl> {
            const localVarFetchArgs = ManagementApiFetchParamCreator(configuration).reset(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Send an e-mail to test mail server gateway
         * @param {MailData} MailData 
         * @param {boolean} UseKafka 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendTestMail(MailData: MailData, UseKafka: boolean, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
            const localVarFetchArgs = ManagementApiFetchParamCreator(configuration).sendTestMail(MailData, UseKafka, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Test JSON ISimulationEntityPost injection (direct or KAFKA)
         * @param {SimulationEntityPostData} SimulationEntityPostData 
         * @param {boolean} UseKafka 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testSimulationEntityPost(SimulationEntityPostData: SimulationEntityPostData, UseKafka: boolean, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
            const localVarFetchArgs = ManagementApiFetchParamCreator(configuration).testSimulationEntityPost(SimulationEntityPostData, UseKafka, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * ManagementApi - factory interface
 * @export
 */
export const ManagementApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Add mail account to mail server (e.g. \"user@world.com\") 
         * @summary Add mail account
         * @param {string} Password The mail account password
         * @param {string} Account The mail account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAccount(Password: string, Account: string, options?: any) {
            return ManagementApiFp(configuration).addAccount(Password, Account, options)(fetch, basePath);
        },
        /**
         * Delete mail account to mail server \"user@world.com\" 
         * @summary Delete mail account
         * @param {string} Account The mail account
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAccount(Account: string, options?: any) {
            return ManagementApiFp(configuration).deleteAccount(Account, options)(fetch, basePath);
        },
        /**
         * Get status of server
         * @summary Get status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus(options?: any) {
            return ManagementApiFp(configuration).getStatus(options)(fetch, basePath);
        },
        /**
         * Get mail accounts
         * @summary Get mail accounts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mailAccounts(options?: any) {
            return ManagementApiFp(configuration).mailAccounts(options)(fetch, basePath);
        },
        /**
         * Reset database
         * @summary Reset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reset(options?: any) {
            return ManagementApiFp(configuration).reset(options)(fetch, basePath);
        },
        /**
         * 
         * @summary Send an e-mail to test mail server gateway
         * @param {MailData} MailData 
         * @param {boolean} UseKafka 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendTestMail(MailData: MailData, UseKafka: boolean, options?: any) {
            return ManagementApiFp(configuration).sendTestMail(MailData, UseKafka, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Test JSON ISimulationEntityPost injection (direct or KAFKA)
         * @param {SimulationEntityPostData} SimulationEntityPostData 
         * @param {boolean} UseKafka 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testSimulationEntityPost(SimulationEntityPostData: SimulationEntityPostData, UseKafka: boolean, options?: any) {
            return ManagementApiFp(configuration).testSimulationEntityPost(SimulationEntityPostData, UseKafka, options)(fetch, basePath);
        },
    };
};

/**
 * ManagementApi - object-oriented interface
 * @export
 * @class ManagementApi
 * @extends {BaseAPI}
 */
export class ManagementApi extends BaseAPI {
    /**
     * Add mail account to mail server (e.g. \"user@world.com\") 
     * @summary Add mail account
     * @param {string} Password The mail account password
     * @param {string} Account The mail account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementApi
     */
    public addAccount(Password: string, Account: string, options?: any) {
        return ManagementApiFp(this.configuration).addAccount(Password, Account, options)(this.fetch, this.basePath);
    }

    /**
     * Delete mail account to mail server \"user@world.com\" 
     * @summary Delete mail account
     * @param {string} Account The mail account
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementApi
     */
    public deleteAccount(Account: string, options?: any) {
        return ManagementApiFp(this.configuration).deleteAccount(Account, options)(this.fetch, this.basePath);
    }

    /**
     * Get status of server
     * @summary Get status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementApi
     */
    public getStatus(options?: any) {
        return ManagementApiFp(this.configuration).getStatus(options)(this.fetch, this.basePath);
    }

    /**
     * Get mail accounts
     * @summary Get mail accounts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementApi
     */
    public mailAccounts(options?: any) {
        return ManagementApiFp(this.configuration).mailAccounts(options)(this.fetch, this.basePath);
    }

    /**
     * Reset database
     * @summary Reset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementApi
     */
    public reset(options?: any) {
        return ManagementApiFp(this.configuration).reset(options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Send an e-mail to test mail server gateway
     * @param {MailData} MailData 
     * @param {boolean} UseKafka 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementApi
     */
    public sendTestMail(MailData: MailData, UseKafka: boolean, options?: any) {
        return ManagementApiFp(this.configuration).sendTestMail(MailData, UseKafka, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Test JSON ISimulationEntityPost injection (direct or KAFKA)
     * @param {SimulationEntityPostData} SimulationEntityPostData 
     * @param {boolean} UseKafka 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementApi
     */
    public testSimulationEntityPost(SimulationEntityPostData: SimulationEntityPostData, UseKafka: boolean, options?: any) {
        return ManagementApiFp(this.configuration).testSimulationEntityPost(SimulationEntityPostData, UseKafka, options)(this.fetch, this.basePath);
    }

}

